/**
 * ============================================================================
 * File: calc.cpp (Interpreter: Stack Machine Version)
 * 
 * --- DESIGN OVERVIEW:
 * This is an industrial-style interpreter. It does not use the GoF AST.
 * Instead, it works in two phases:
 * 1. Compiler (Recursive Descent): Parses the math string and generates 
 *    a linear array of instructions (Bytecode).
 * 2. Virtual Machine: Evaluates the bytecode using a Stack.
 * 
 * Usage: ./calc [-p] "<math_expression>"
 * The '-p' flag prints the generated bytecode before evaluating.
 * ============================================================================
 */

#include <iostream>
#include <vector>
#include <string>
#include <cmath>
#include <stdexcept>
#include <cctype>

//=============================================================================
// BLOCK 1: BYTECODE & TOKENS DEFINITIONS
//=============================================================================

enum class OpCode 
{ 
   PUSH, ADD, SUB, MUL, DIV, POW, CHSGN, 
   SIN, COS, TAN, ASIN, ACOS, ATAN, SQRT, LN, LOG, EXP 
};

struct Instruction 
{
   OpCode code;
   double value{0.0}; // Only used if code is PUSH
};

enum class TokenType 
{ 
   NUMBER, FUNCTION, PLUS, MINUS, MUL, DIV, POW, LPAREN, RPAREN, END_OF_FILE 
};

struct Token 
{
   TokenType type;
   double value{0.0};
   std::string name{""};
};

//=============================================================================
// BLOCK 2: LEXER (Scanner)
//=============================================================================
class Lexer
{
private:
   std::string input_;
   size_t pos_{0};
   Token currentToken_;

   void advanceChar() { pos_++; }
   char peek() const { return (pos_ < input_.size()) ? input_[pos_] : '\0'; }

public:
   explicit Lexer(std::string input) : input_{std::move(input)} 
   {
      nextToken(); // Load first token
   }

   Token getToken() const { return currentToken_; }

   void nextToken()
   {
      while (isspace(peek())) advanceChar();

      if (pos_ >= input_.size())
      {
         currentToken_ = {TokenType::END_OF_FILE};
         return;
      }

      char c = peek();

      if (isdigit(c) || c == '.')
      {
         size_t length;
         double val = std::stod(input_.substr(pos_), &length);
         pos_ += length;
         currentToken_ = {TokenType::NUMBER, val, ""};
      }
      else if (isalpha(c))
      {
         std::string funcName = "";
         while (isalpha(peek()))
         {
            funcName += peek();
            advanceChar();
         }
         currentToken_ = {TokenType::FUNCTION, 0.0, funcName};
      }
      else
      {
         switch (c)
         {
            case '+': currentToken_ = {TokenType::PLUS}; break;
            case '-': currentToken_ = {TokenType::MINUS}; break;
            case '*': currentToken_ = {TokenType::MUL}; break;
            case '/': currentToken_ = {TokenType::DIV}; break;
            case '^': currentToken_ = {TokenType::POW}; break;
            case '(': currentToken_ = {TokenType::LPAREN}; break;
            case ')': currentToken_ = {TokenType::RPAREN}; break;
            default:  throw std::runtime_error(std::string("Syntax error: Unknown character: ") + c);
         }
         advanceChar();
      }
   }
};

//=============================================================================
// BLOCK 3: COMPILER (Recursive Descent Parser)
//=============================================================================
class Compiler
{
private:
   Lexer lexer_;
   std::vector<Instruction> program_;

   void match(TokenType expected)
   {
      if (lexer_.getToken().type == expected) lexer_.nextToken();
      else throw std::runtime_error("Syntax error: Unexpected token");
   }

   void emit(OpCode code, double value = 0.0)
   {
      program_.push_back({code, value});
   }

   // --- Grammar Rules ---

   void parsePrimary()
   {
      Token t = lexer_.getToken();
      if (t.type == TokenType::NUMBER)
      {
         emit(OpCode::PUSH, t.value);
         match(TokenType::NUMBER);
      }
      else if (t.type == TokenType::LPAREN)
      {
         match(TokenType::LPAREN);
         parseExpression();
         match(TokenType::RPAREN);
      }
      else if (t.type == TokenType::FUNCTION)
      {
         std::string func = t.name;
         match(TokenType::FUNCTION);
         match(TokenType::LPAREN);
         parseExpression();
         match(TokenType::RPAREN);

         if (func == "sin")       emit(OpCode::SIN);
         else if (func == "cos")  emit(OpCode::COS);
         else if (func == "tan")  emit(OpCode::TAN);
         else if (func == "asin") emit(OpCode::ASIN);
         else if (func == "acos") emit(OpCode::ACOS);
         else if (func == "atan") emit(OpCode::ATAN);
         else if (func == "sqrt") emit(OpCode::SQRT);
         else if (func == "ln")   emit(OpCode::LN);
         else if (func == "log")  emit(OpCode::LOG);
         else if (func == "exp")  emit(OpCode::EXP);
         else throw std::runtime_error("Error: Unknown function: " + func);
      }
      else throw std::runtime_error("Syntax error in primary expression");
   }

   void parseSigned()
   {
      Token t = lexer_.getToken();
      if (t.type == TokenType::PLUS)
      {
         match(TokenType::PLUS);
         parsePrimary();
      }
      else if (t.type == TokenType::MINUS)
      {
         match(TokenType::MINUS);
         parsePrimary();
         emit(OpCode::CHSGN);
      }
      else parsePrimary();
   }

   void parseExponent()
   {
      parseSigned();
      while (lexer_.getToken().type == TokenType::POW)
      {
         match(TokenType::POW);
         parseSigned();
         emit(OpCode::POW);
      }
   }

   void parseMultiplicative()
   {
      parseExponent();
      while (lexer_.getToken().type == TokenType::MUL || 
             lexer_.getToken().type == TokenType::DIV)
      {
         TokenType op = lexer_.getToken().type;
         match(op);
         parseExponent();
         if (op == TokenType::MUL) emit(OpCode::MUL);
         else emit(OpCode::DIV);
      }
   }

   void parseAdditive()
   {
      parseMultiplicative();
      while (lexer_.getToken().type == TokenType::PLUS || 
             lexer_.getToken().type == TokenType::MINUS)
      {
         TokenType op = lexer_.getToken().type;
         match(op);
         parseMultiplicative();
         if (op == TokenType::PLUS) emit(OpCode::ADD);
         else emit(OpCode::SUB);
      }
   }

   void parseExpression()
   {
      parseAdditive();
   }

public:
   explicit Compiler(const std::string& source) : lexer_(source) { }

   std::vector<Instruction> compile()
   {
      parseExpression();
      if (lexer_.getToken().type != TokenType::END_OF_FILE)
         throw std::runtime_error("Syntax error: Unexpected tokens at end");
      return program_;
   }
};

//=============================================================================
// BLOCK 4: VIRTUAL MACHINE (Evaluator)
//=============================================================================
class VirtualMachine
{
private:
   std::string opcodeToString(OpCode code) const
   {
      switch (code)
      {
         case OpCode::PUSH:  return "PUSH";
         case OpCode::ADD:   return "ADD";
         case OpCode::SUB:   return "SUB";
         case OpCode::MUL:   return "MUL";
         case OpCode::DIV:   return "DIV";
         case OpCode::POW:   return "POW";
         case OpCode::CHSGN: return "CHSGN";
         case OpCode::SIN:   return "SIN";
         case OpCode::COS:   return "COS";
         case OpCode::TAN:   return "TAN";
         case OpCode::ASIN:  return "ASIN";
         case OpCode::ACOS:  return "ACOS";
         case OpCode::ATAN:  return "ATAN";
         case OpCode::SQRT:  return "SQRT";
         case OpCode::LN:    return "LN";
         case OpCode::LOG:   return "LOG";
         case OpCode::EXP:   return "EXP";
         default:            return "UNKNOWN";
      }
   }

public:
   void printProgram(const std::vector<Instruction>& program) const
   {
      std::cout << "\n--- Bytecode Program ---\n";
      for (const auto& inst : program)
      {
         std::cout << "  " << opcodeToString(inst.code);
         if (inst.code == OpCode::PUSH) std::cout << " " << inst.value;
         std::cout << "\n";
      }
      std::cout << "------------------------\n\n";
   }

   double evaluate(const std::vector<Instruction>& program) const
   {
      std::vector<double> stack;

      for (const auto& inst : program)
      {
         if (inst.code == OpCode::PUSH)
         {
            stack.push_back(inst.value);
            continue;
         }

         // Handle Unary Operations
         if (inst.code >= OpCode::CHSGN)
         {
            if (stack.empty()) throw std::runtime_error("Error: Stack underflow on unary op");
            double val = stack.back();
            stack.pop_back();

            switch (inst.code)
            {
               case OpCode::CHSGN: stack.push_back(-val); break;
               case OpCode::SIN:   stack.push_back(std::sin(val)); break;
               case OpCode::COS:   stack.push_back(std::cos(val)); break;
               case OpCode::TAN:   stack.push_back(std::tan(val)); break;
               case OpCode::ASIN:  stack.push_back(std::asin(val)); break;
               case OpCode::ACOS:  stack.push_back(std::acos(val)); break;
               case OpCode::ATAN:  stack.push_back(std::atan(val)); break;
               case OpCode::EXP:   stack.push_back(std::exp(val)); break;
               case OpCode::SQRT:  
                  if (val < 0) throw std::runtime_error("Error: sqrt of negative number");
                  stack.push_back(std::sqrt(val)); break;
               case OpCode::LN:
                  if (val <= 0) throw std::runtime_error("Error: ln of non-positive number");
                  stack.push_back(std::log(val)); break;
               case OpCode::LOG:
                  if (val <= 0) throw std::runtime_error("Error: log of non-positive number");
                  stack.push_back(std::log10(val)); break;
               default: break;
            }
            continue;
         }

         // Handle Binary Operations
         if (stack.size() < 2) throw std::runtime_error("Error: Stack underflow on binary op");
         double right = stack.back(); stack.pop_back();
         double left  = stack.back(); stack.pop_back();

         switch (inst.code)
         {
            case OpCode::ADD: stack.push_back(left + right); break;
            case OpCode::SUB: stack.push_back(left - right); break;
            case OpCode::MUL: stack.push_back(left * right); break;
            case OpCode::DIV: 
               if (right == 0.0) throw std::runtime_error("Error: Division by zero");
               stack.push_back(left / right); break;
            case OpCode::POW: stack.push_back(std::pow(left, right)); break;
            default: break;
         }
      }

      if (stack.size() != 1) throw std::runtime_error("Error: Unbalanced evaluation stack");
      return stack.back();
   }
};

//=============================================================================
// BLOCK 5: COMMAND LINE INTERFACE (Main)
//=============================================================================
int main(int argc, char* argv[])
{
   std::cout << "=== CHAIN OF RESPONSIBILITY (STACK MACHINE) ===\n" << std::endl;

   if (argc < 2 || argc > 3)
   {
      std::cerr << "Usage: calc [-p] \"<math_expression>\"\n"
                << "Note: Trigonometric functions are in radians\n";
      return 1;
   }

   bool printInternals = false;
   std::string sourceCode;

   if (argc == 3)
   {
      std::string flag = argv[1];
      if (flag == "-p")
      {
         printInternals = true;
         sourceCode = argv[2];
      }
      else
      {
         std::cerr << "Error: Unknown flag '" << flag << "'. Only '-p' is supported.\n";
         return 1;
      }
   }
   else
   {
      sourceCode = argv[1];
   }

   try
   {
      // 1. Compile source code into bytecode
      Compiler compiler(sourceCode);
      std::vector<Instruction> program = compiler.compile();

      VirtualMachine vm;

      // 2. Optionally print the bytecode
      if (printInternals) vm.printProgram(program);

      // 3. Evaluate the bytecode and print the result
      double result = vm.evaluate(program);
      std::cout << "Result: " << result << "\n";
   }
   catch (const std::exception& e)
   {
      std::cerr << e.what() << "\n";
      return 1;
   }
}

//================================================================================ END
